name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
        cache: true
    
    - name: Download dependencies
      run: go mod download
    
    - name: Check code formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code formatting issues found:"
          gofmt -s -d .
          exit 1
        fi
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m --out-format=github-actions
        skip-pkg-cache: true
        skip-build-cache: true
      continue-on-error: true
    
    - name: Check for ineffassign
      run: |
        go install github.com/gordonklaus/ineffassign@latest
        ineffassign ./...
      continue-on-error: true
    
    - name: Check for unused packages
      run: |
        go install github.com/kisielk/errcheck@latest
        errcheck ./...
      continue-on-error: true

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: '-no-fail -fmt sarif -out gosec-report.sarif ./...'
      continue-on-error: true
    
    - name: Upload Gosec results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: gosec-report.sarif
      continue-on-error: true
